blank_issues_enabled: false
contact_links:
    - name: Ask a question
      url: https://github.com/epycsolutions/exoticicon/discussions
      about: Ask questions and discuss topics with other community members
    - name: Chat with other community members
      url: https://discord.gg/hWhcQ5T
      about: The official Epyc Solutions Discord community!
